# Generated by Django 4.0.3 on 2022-08-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
