# Generated by Django 4.0.3 on 2022-08-27 02:51

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_written', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250, verbose_name='Post title')),
                ('slug', models.SlugField(blank=True, max_length=250, null=True, unique=True)),
                ('thumbnail_img', models.ImageField(blank=True, null=True, upload_to='thumbnail/', verbose_name='Thumbnail image 600x600 px')),
                ('post_snippet', models.TextField(max_length=250, null=True, verbose_name='Post snippet')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_written'],
            },
        ),
    ]
